name: Measure TeX Live Setup Time

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    name: Setup TeX Live in Docker
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Verify TeX Live Installation
        run: lualatex --version

  linux:
    name: Setup TeX Live on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install TeX Live
        run: |
          sudo apt update
          sudo apt install -y texlive-full
      - name: Verify TeX Live Installation
        run: lualatex --version

  windows:
    name: Setup TeX Live on Windows
    runs-on: windows-latest

    steps:
      - name: Set Execution Policy
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
        shell: pwsh

      - name: Download and Extract TeX Live Installer
        run: |
          $installerUrl = "https://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip"
          $installDir = "$env:TEMP\install-tl"
          Invoke-WebRequest -Uri $installerUrl -OutFile "$installDir.zip"
          Expand-Archive -Path "$installDir.zip" -DestinationPath $installDir -Force
        shell: pwsh

      - name: Locate Installer Directory
        run: |
          $installSubDir = Get-ChildItem -Path $env:TEMP\install-tl | Where-Object { $_.Name -match "install-tl-\d+" } | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          echo "INSTALL_PATH=$env:TEMP\install-tl\$($installSubDir.Name)" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Create Installation Profile
        run: |
          @"
          selected_scheme scheme-full
          TEXDIR C:\texlive\2024
          option_path 1
          option_doc 0
          option_src 0
          "@ | Out-File -Encoding ascii "$env:INSTALL_PATH\install-profile.txt"
        shell: pwsh

      - name: Run TeX Live Installer with Elevated Privileges
        run: |
          Start-Process -FilePath "$env:INSTALL_PATH\tlpkg\tlperl\bin\perl.exe" -ArgumentList "`"$env:INSTALL_PATH\install-tl`" -no-gui -profile=`"$env:INSTALL_PATH\install-profile.txt`"" -Wait -NoNewWindow
        shell: pwsh

      - name: Add TeX Live to PATH
        run: |
          echo "C:\texlive\2024\bin\windows" | Out-File -FilePath $env:GITHUB_PATH -Append
        shell: pwsh

      - name: Verify TeX Live Installation
        run: |
          lualatex --version
        shell: pwsh
