name: Measure TeX Live Setup Time

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    name: Setup TeX Live in Docker
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Verify TeX Live Installation
        run: lualatex --version

  linux:
    name: Setup TeX Live on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install TeX Live
        run: |
          sudo apt update
          sudo apt install -y texlive-full
      - name: Verify TeX Live Installation
        run: lualatex --version

  windows:
    name: Setup TeX Live on Windows
    runs-on: windows-latest
    steps:
      - name: Setup Environment
        shell: pwsh
        run: |
          echo "INSTALL_DIR=$env:TEMP\install-tl" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "TEXLIVE_BIN=C:\texlive\2024\bin\windows" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Download and Extract Installer
        shell: pwsh
        run: |
          $installerUrl = "https://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip"
          $zipPath = "$env:INSTALL_DIR.zip"
          Invoke-WebRequest -Uri $installerUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $env:INSTALL_DIR -Force

      - name: Set Installer Path
        shell: pwsh
        run: |
          $installerDir = Get-ChildItem -Path $env:INSTALL_DIR | Where-Object { $_.Name -match 'install-tl-\d+' } | Select-Object -First 1 -ExpandProperty FullName
          echo "INSTALL_PATH=$installerDir" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create Installation Profile
        shell: pwsh
        run: |
          $profileContent = @"
          selected_scheme scheme-full
          TEXDIR C:\texlive\2024
          option_path 1
          option_doc 0
          option_src 0
          "@
          $profilePath = "$env:INSTALL_PATH\install-profile.txt"
          $profileContent | Out-File -Encoding ascii $profilePath

      - name: Run TeX Live Installer
        shell: pwsh
        run: |
          & "$env:INSTALL_PATH\tlpkg\tlperl\bin\perl.exe" "$env:INSTALL_PATH\install-tl" -no-gui -profile="$env:INSTALL_PATH\install-profile.txt"

      - name: Add TeX Live to PATH
        shell: pwsh
        run: echo "$env:TEXLIVE_BIN" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Verify TeX Live Installation
        shell: pwsh
        run: lualatex --version
