name: Measure TeX Live Setup Time

on:
  workflow_dispatch:

jobs:
  docker:
    name: Setup TeX Live in Docker
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Verify TeX Live Installation
        run: lualatex --version

  linux:
    name: Setup TeX Live on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install TeX Live
        run: |
          sudo apt update
          sudo apt install -y texlive-full
      - name: Verify TeX Live Installation
        run: lualatex --version

  windows:
    name: Setup TeX Live on Windows
    runs-on: windows-latest
    steps:
      - name: Download TeX Live Installer
        run: |
          $installerUrl = "https://mirror.ctan.org/systems/texlive/tlnet/install-tl-windows.exe"
          $installerPath = "$env:TEMP\install-tl-windows.exe"
          Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
        shell: pwsh

      - name: Install TeX Live
        run: |
          Start-Process -FilePath "$env:TEMP\install-tl-windows.exe" -ArgumentList "-no-gui" -Wait -NoNewWindow
        shell: pwsh

      - name: Verify TeX Live Installation
        run: |
          $texliveBin = "C:\texlive\2024\bin\windows"
          $env:Path += ";$texliveBin"
          lualatex --version
        shell: pwsh
